#pragma once

#define MAX_ZEPHYR_SERVOS 16
#define SERVO_TIMER_NODE DT_NODELABEL(counter_servo)
#define SERVO_TIMER_ALARM_CHANNEL 0
#define SERVO_TIMER_MIN_DELAY_US 4U
#define SERVO_TIMER_GUARD_US 32U
